// <auto-generated />
namespace David.Products.API.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class correctionnamefields : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(correctionnamefields));
        
        string IMigrationMetadata.Id
        {
            get { return "202001060359177_correction name fields"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
